### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by Rmail733** [Macadoshis/stalker-to-m3u#1]
Hello, how to use this script.. please describe🙏🙏

**Comment by sbenbouzid** [comment]
Hello,

Thank you for your interest.

Sorry I didn't find the time to write a proper README yet and I know it's much needed for people to use it except that just me.

Here is the how-to in short (don't want to make it too neat and detailed here as there'll be a README for that).

1) Install [NodeJS](https://nodejs.org/en/download) and make sure `npm` exists in your PATH. There's no OS+architecture specific dependency so it should run in all environments (windows, linux, mac, ...).

2) Only IPTV and VOD are supported yet (Series are not exportable, will come in a future development).

3) Fill in the `config.json`  with your stalker provider _http://my.dns.com:8080/stalker_portal/c/ + MAC: 00:1A:79:12:34:56_.

- `"hostname"`: DNS as in **my.dns.com**,
- `"port"`: port as in **8080** (use 80 if there is no port in the URL),
- `"contextPath"`: (optional text, default is `""`) context path as in **stalker_portal**,
- `"mac"`:  full mac address as in "00:1A:79:12:34:56",
- `"tvgIdPreFill"`: (optional boolean, default is `false`) tries to assign a EPG tvid from existing mapping in `tvg.json`,
- `"computeUrlLink"`: (optional boolean, default is `false`) resolve stream URL otherwise set it to STB provider default. Set it to `false` for M3U generation for EPG purpose only, set it to `true` otherwise (most cases),
- `"vodMaxPagePerGenre"`: (optional integer, default is `2`) max number of pages per category to fetch the videos from. The more pages you set, the longer the generation will take.

4) Fetch the categories, by calling either `npm run groups iptv` or `npm run groups vod`. If your config.json settings are correct, this will generate the categories in an output file `groups.txt`.  The command will end with an error in case your provider is invalid (connection refused, 401, 403, ...).
Feel free to only select the desired categories by removing the extra lines. The more categories there are, the longer the generation will take.

5) Generate the m3u file, by calling respectively either `npm run m3u iptv` or `npm run m3u vod`.
The script will show you the progression of the generation in percentage. At the end if there's no error, this will generate an output file respectively **m3u-my.dns.com.m3u** or **vod-my.dns.com.m3u**.

**Comment by Macadoshis** [comment]
Hello,

Thank you for your interest.

Sorry I didn't find the time to write a proper README yet and I know it's much needed for people to use it except that just me.

Here is the how-to in short (don't want to make it too neat and detailed here as there'll be a README for that).

1) Install [NodeJS](https://nodejs.org/en/download) and make sure `npm` exists in your PATH. There's no OS+architecture specific dependency so it should run in all environments (windows, linux, mac, ...).

2) Only IPTV and VOD are supported yet (Series are not exportable, will come in a future development).

3) Fill in the `config.json`  with your stalker provider _http://my.dns.com:8080/stalker_portal/c/ + MAC: 00:1A:79:12:34:56_.

- `"hostname"`: DNS as in **my.dns.com**,
- `"port"`: port as in **8080** (use 80 if there is no port in the URL),
- `"contextPath"`: (optional text, default is `""`) context path as in **stalker_portal**,
- `"mac"`:  full mac address as in "00:1A:79:12:34:56",
- `"tvgIdPreFill"`: (optional boolean, default is `false`) tries to assign a EPG tvid from existing mapping in `tvg.json`,
- `"computeUrlLink"`: (optional boolean, default is `false`) resolve stream URL otherwise set it to STB provider default. Set it to `false` for M3U generation for EPG purpose only, set it to `true` otherwise (most cases),
- `"vodMaxPagePerGenre"`: (optional integer, default is `2`) max number of pages per category to fetch the videos from. The more pages you set, the longer the generation will take.

4) Fetch the categories, by calling either `npm run groups iptv` or `npm run groups vod`. If your config.json settings are correct, this will generate the categories in an output file `groups.txt`.  The command will end with an error in case your provider is invalid (connection refused, 401, 403, ...).
Feel free to only select the desired categories by removing the extra lines. The more categories there are, the longer the generation will take.

5) Generate the m3u file, by calling respectively either `npm run m3u iptv` or `npm run m3u vod`.
The script will show you the progression of the generation in percentage. At the end if there's no error, this will generate an output file respectively **m3u-my.dns.com.m3u** or **vod-my.dns.com.m3u**.

**Comment by Rmail733** [comment]
Can I use this script for jiotv.be stalker portal to m3u..by webhosting.. please help me for jiotv.be portal webhosting..🙏🙏🙏

**Comment by Macadoshis** [comment]
Sure, if it's stalker protocol it should work. Did you try ?

Should work with following **config.json** : 

```
{
    "hostname": "jiotv.be",
    "port": 80,
    "contextPath": "stalker_portal",
    "mac": "00:1A:79:xx:xx:xx",
    "tvgIdPreFill": true,
    "computeUrlLink": true,
    "vodMaxPagePerGenre": 10
}
```

Tell me if works or print your error otherwise.
